"""rename_price_nl_to_price_ca

Revision ID: 2512e3624815
Revises: 6db62106d2e1
Create Date: 2026-02-23 21:02:14.433663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2512e3624815'
down_revision: Union[str, Sequence[str], None] = '6db62106d2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brickset_data', sa.Column('price_ca', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('brickset_data', 'price_nl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brickset_data', sa.Column('price_nl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('brickset_data', 'price_ca')
    # ### end Alembic commands ###
