"""add_brickset_data

Revision ID: 6db62106d2e1
Revises: efc3e7c00129
Create Date: 2026-02-23 20:59:06.313920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6db62106d2e1'
down_revision: Union[str, Sequence[str], None] = 'efc3e7c00129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brickset_data',
    sa.Column('set_num', sa.String(length=20), nullable=False),
    sa.Column('brickset_id', sa.Integer(), nullable=True),
    sa.Column('price_nl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_uk', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_us', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_de', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('packaging_type', sa.String(length=50), nullable=True),
    sa.Column('age_min', sa.SmallInteger(), nullable=True),
    sa.Column('age_max', sa.SmallInteger(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('barcode_ean', sa.String(length=20), nullable=True),
    sa.Column('barcode_upc', sa.String(length=20), nullable=True),
    sa.Column('item_number', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('owned_by', sa.Integer(), nullable=True),
    sa.Column('wanted_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_num'], ['sets.set_num'], ),
    sa.PrimaryKeyConstraint('set_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brickset_data')
    # ### end Alembic commands ###
