"""initial

Revision ID: e3fe20609d57
Revises: 
Create Date: 2026-02-23 20:09:02.648901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fe20609d57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rgb', sa.String(length=6), nullable=False),
    sa.Column('is_trans', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minifigs',
    sa.Column('fig_num', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('num_parts', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('fig_num')
    )
    op.create_table('part_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('part_num', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('part_cat_id', sa.Integer(), nullable=False),
    sa.Column('part_material', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['part_cat_id'], ['part_categories.id'], ),
    sa.PrimaryKeyConstraint('part_num')
    )
    op.create_table('sets',
    sa.Column('set_num', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('num_parts', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('set_num')
    )
    op.create_table('elements',
    sa.Column('element_id', sa.String(length=20), nullable=False),
    sa.Column('part_num', sa.String(length=20), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['part_num'], ['parts.part_num'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['set_num'], ['sets.set_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rel_type', sa.String(length=1), nullable=False),
    sa.Column('child_part_num', sa.String(length=20), nullable=False),
    sa.Column('parent_part_num', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_part_num'], ['parts.part_num'], ),
    sa.ForeignKeyConstraint(['parent_part_num'], ['parts.part_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_minifigs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('fig_num', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fig_num'], ['minifigs.fig_num'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('part_num', sa.String(length=20), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_spare', sa.Boolean(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['part_num'], ['parts.part_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['set_num'], ['sets.set_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_sets')
    op.drop_table('inventory_parts')
    op.drop_table('inventory_minifigs')
    op.drop_table('part_relationships')
    op.drop_table('inventories')
    op.drop_table('elements')
    op.drop_table('sets')
    op.drop_table('parts')
    op.drop_table('themes')
    op.drop_table('part_categories')
    op.drop_table('minifigs')
    op.drop_table('colors')
    # ### end Alembic commands ###
