"""remove_fk_inventories_set_num

Revision ID: efc3e7c00129
Revises: e3fe20609d57
Create Date: 2026-02-23 20:15:25.653034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc3e7c00129'
down_revision: Union[str, Sequence[str], None] = 'e3fe20609d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventories_set_num_fkey'), 'inventories', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('inventories_set_num_fkey'), 'inventories', 'sets', ['set_num'], ['set_num'])
    # ### end Alembic commands ###
